/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateOrUpdateThreadTagRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrUpdateThreadTagRequest{}

// CreateOrUpdateThreadTagRequest struct for CreateOrUpdateThreadTagRequest
type CreateOrUpdateThreadTagRequest struct {
	Name string `json:"name"`
	EmojiId *string `json:"emoji_id,omitempty" validate:"regexp=^(0|[1-9][0-9]*)$"`
	EmojiName NullableString `json:"emoji_name,omitempty"`
	Moderated NullableBool `json:"moderated,omitempty"`
}

type _CreateOrUpdateThreadTagRequest CreateOrUpdateThreadTagRequest

// NewCreateOrUpdateThreadTagRequest instantiates a new CreateOrUpdateThreadTagRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrUpdateThreadTagRequest(name string) *CreateOrUpdateThreadTagRequest {
	this := CreateOrUpdateThreadTagRequest{}
	this.Name = name
	return &this
}

// NewCreateOrUpdateThreadTagRequestWithDefaults instantiates a new CreateOrUpdateThreadTagRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrUpdateThreadTagRequestWithDefaults() *CreateOrUpdateThreadTagRequest {
	this := CreateOrUpdateThreadTagRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateOrUpdateThreadTagRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateThreadTagRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateOrUpdateThreadTagRequest) SetName(v string) {
	o.Name = v
}

// GetEmojiId returns the EmojiId field value if set, zero value otherwise.
func (o *CreateOrUpdateThreadTagRequest) GetEmojiId() string {
	if o == nil || IsNil(o.EmojiId) {
		var ret string
		return ret
	}
	return *o.EmojiId
}

// GetEmojiIdOk returns a tuple with the EmojiId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrUpdateThreadTagRequest) GetEmojiIdOk() (*string, bool) {
	if o == nil || IsNil(o.EmojiId) {
		return nil, false
	}
	return o.EmojiId, true
}

// HasEmojiId returns a boolean if a field has been set.
func (o *CreateOrUpdateThreadTagRequest) HasEmojiId() bool {
	if o != nil && !IsNil(o.EmojiId) {
		return true
	}

	return false
}

// SetEmojiId gets a reference to the given string and assigns it to the EmojiId field.
func (o *CreateOrUpdateThreadTagRequest) SetEmojiId(v string) {
	o.EmojiId = &v
}

// GetEmojiName returns the EmojiName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateThreadTagRequest) GetEmojiName() string {
	if o == nil || IsNil(o.EmojiName.Get()) {
		var ret string
		return ret
	}
	return *o.EmojiName.Get()
}

// GetEmojiNameOk returns a tuple with the EmojiName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateThreadTagRequest) GetEmojiNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EmojiName.Get(), o.EmojiName.IsSet()
}

// HasEmojiName returns a boolean if a field has been set.
func (o *CreateOrUpdateThreadTagRequest) HasEmojiName() bool {
	if o != nil && o.EmojiName.IsSet() {
		return true
	}

	return false
}

// SetEmojiName gets a reference to the given NullableString and assigns it to the EmojiName field.
func (o *CreateOrUpdateThreadTagRequest) SetEmojiName(v string) {
	o.EmojiName.Set(&v)
}
// SetEmojiNameNil sets the value for EmojiName to be an explicit nil
func (o *CreateOrUpdateThreadTagRequest) SetEmojiNameNil() {
	o.EmojiName.Set(nil)
}

// UnsetEmojiName ensures that no value is present for EmojiName, not even an explicit nil
func (o *CreateOrUpdateThreadTagRequest) UnsetEmojiName() {
	o.EmojiName.Unset()
}

// GetModerated returns the Moderated field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateOrUpdateThreadTagRequest) GetModerated() bool {
	if o == nil || IsNil(o.Moderated.Get()) {
		var ret bool
		return ret
	}
	return *o.Moderated.Get()
}

// GetModeratedOk returns a tuple with the Moderated field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateOrUpdateThreadTagRequest) GetModeratedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.Moderated.Get(), o.Moderated.IsSet()
}

// HasModerated returns a boolean if a field has been set.
func (o *CreateOrUpdateThreadTagRequest) HasModerated() bool {
	if o != nil && o.Moderated.IsSet() {
		return true
	}

	return false
}

// SetModerated gets a reference to the given NullableBool and assigns it to the Moderated field.
func (o *CreateOrUpdateThreadTagRequest) SetModerated(v bool) {
	o.Moderated.Set(&v)
}
// SetModeratedNil sets the value for Moderated to be an explicit nil
func (o *CreateOrUpdateThreadTagRequest) SetModeratedNil() {
	o.Moderated.Set(nil)
}

// UnsetModerated ensures that no value is present for Moderated, not even an explicit nil
func (o *CreateOrUpdateThreadTagRequest) UnsetModerated() {
	o.Moderated.Unset()
}

func (o CreateOrUpdateThreadTagRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrUpdateThreadTagRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if !IsNil(o.EmojiId) {
		toSerialize["emoji_id"] = o.EmojiId
	}
	if o.EmojiName.IsSet() {
		toSerialize["emoji_name"] = o.EmojiName.Get()
	}
	if o.Moderated.IsSet() {
		toSerialize["moderated"] = o.Moderated.Get()
	}
	return toSerialize, nil
}

func (o *CreateOrUpdateThreadTagRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateOrUpdateThreadTagRequest := _CreateOrUpdateThreadTagRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateOrUpdateThreadTagRequest)

	if err != nil {
		return err
	}

	*o = CreateOrUpdateThreadTagRequest(varCreateOrUpdateThreadTagRequest)

	return err
}

type NullableCreateOrUpdateThreadTagRequest struct {
	value *CreateOrUpdateThreadTagRequest
	isSet bool
}

func (v NullableCreateOrUpdateThreadTagRequest) Get() *CreateOrUpdateThreadTagRequest {
	return v.value
}

func (v *NullableCreateOrUpdateThreadTagRequest) Set(val *CreateOrUpdateThreadTagRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrUpdateThreadTagRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrUpdateThreadTagRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrUpdateThreadTagRequest(val *CreateOrUpdateThreadTagRequest) *NullableCreateOrUpdateThreadTagRequest {
	return &NullableCreateOrUpdateThreadTagRequest{value: val, isSet: true}
}

func (v NullableCreateOrUpdateThreadTagRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrUpdateThreadTagRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


