/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// ErrorDetails - struct for ErrorDetails
type ErrorDetails struct {
	InnerErrors *InnerErrors
	MapmapOfStringErrorDetails *map[string]ErrorDetails
}

// InnerErrorsAsErrorDetails is a convenience function that returns InnerErrors wrapped in ErrorDetails
func InnerErrorsAsErrorDetails(v *InnerErrors) ErrorDetails {
	return ErrorDetails{
		InnerErrors: v,
	}
}

// map[string]ErrorDetailsAsErrorDetails is a convenience function that returns map[string]ErrorDetails wrapped in ErrorDetails
func MapmapOfStringErrorDetailsAsErrorDetails(v *map[string]ErrorDetails) ErrorDetails {
	return ErrorDetails{
		MapmapOfStringErrorDetails: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ErrorDetails) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into InnerErrors
	err = newStrictDecoder(data).Decode(&dst.InnerErrors)
	if err == nil {
		jsonInnerErrors, _ := json.Marshal(dst.InnerErrors)
		if string(jsonInnerErrors) == "{}" { // empty struct
			dst.InnerErrors = nil
		} else {
			if err = validator.Validate(dst.InnerErrors); err != nil {
				dst.InnerErrors = nil
			} else {
				match++
			}
		}
	} else {
		dst.InnerErrors = nil
	}

	// try to unmarshal data into MapmapOfStringErrorDetails
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringErrorDetails)
	if err == nil {
		jsonMapmapOfStringErrorDetails, _ := json.Marshal(dst.MapmapOfStringErrorDetails)
		if string(jsonMapmapOfStringErrorDetails) == "{}" { // empty struct
			dst.MapmapOfStringErrorDetails = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringErrorDetails); err != nil {
				dst.MapmapOfStringErrorDetails = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringErrorDetails = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.InnerErrors = nil
		dst.MapmapOfStringErrorDetails = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ErrorDetails)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ErrorDetails)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ErrorDetails) MarshalJSON() ([]byte, error) {
	if src.InnerErrors != nil {
		return json.Marshal(&src.InnerErrors)
	}

	if src.MapmapOfStringErrorDetails != nil {
		return json.Marshal(&src.MapmapOfStringErrorDetails)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ErrorDetails) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.InnerErrors != nil {
		return obj.InnerErrors
	}

	if obj.MapmapOfStringErrorDetails != nil {
		return obj.MapmapOfStringErrorDetails
	}

	// all schemas are nil
	return nil
}

type NullableErrorDetails struct {
	value *ErrorDetails
	isSet bool
}

func (v NullableErrorDetails) Get() *ErrorDetails {
	return v.value
}

func (v *NullableErrorDetails) Set(val *ErrorDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableErrorDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableErrorDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableErrorDetails(val *ErrorDetails) *NullableErrorDetails {
	return &NullableErrorDetails{value: val, isSet: true}
}

func (v NullableErrorDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableErrorDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


