/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ActivitiesAttachmentResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ActivitiesAttachmentResponse{}

// ActivitiesAttachmentResponse struct for ActivitiesAttachmentResponse
type ActivitiesAttachmentResponse struct {
	Attachment AttachmentResponse `json:"attachment"`
}

type _ActivitiesAttachmentResponse ActivitiesAttachmentResponse

// NewActivitiesAttachmentResponse instantiates a new ActivitiesAttachmentResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActivitiesAttachmentResponse(attachment AttachmentResponse) *ActivitiesAttachmentResponse {
	this := ActivitiesAttachmentResponse{}
	this.Attachment = attachment
	return &this
}

// NewActivitiesAttachmentResponseWithDefaults instantiates a new ActivitiesAttachmentResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActivitiesAttachmentResponseWithDefaults() *ActivitiesAttachmentResponse {
	this := ActivitiesAttachmentResponse{}
	return &this
}

// GetAttachment returns the Attachment field value
func (o *ActivitiesAttachmentResponse) GetAttachment() AttachmentResponse {
	if o == nil {
		var ret AttachmentResponse
		return ret
	}

	return o.Attachment
}

// GetAttachmentOk returns a tuple with the Attachment field value
// and a boolean to check if the value has been set.
func (o *ActivitiesAttachmentResponse) GetAttachmentOk() (*AttachmentResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attachment, true
}

// SetAttachment sets field value
func (o *ActivitiesAttachmentResponse) SetAttachment(v AttachmentResponse) {
	o.Attachment = v
}

func (o ActivitiesAttachmentResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ActivitiesAttachmentResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["attachment"] = o.Attachment
	return toSerialize, nil
}

func (o *ActivitiesAttachmentResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"attachment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varActivitiesAttachmentResponse := _ActivitiesAttachmentResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varActivitiesAttachmentResponse)

	if err != nil {
		return err
	}

	*o = ActivitiesAttachmentResponse(varActivitiesAttachmentResponse)

	return err
}

type NullableActivitiesAttachmentResponse struct {
	value *ActivitiesAttachmentResponse
	isSet bool
}

func (v NullableActivitiesAttachmentResponse) Get() *ActivitiesAttachmentResponse {
	return v.value
}

func (v *NullableActivitiesAttachmentResponse) Set(val *ActivitiesAttachmentResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableActivitiesAttachmentResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableActivitiesAttachmentResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActivitiesAttachmentResponse(val *ActivitiesAttachmentResponse) *NullableActivitiesAttachmentResponse {
	return &NullableActivitiesAttachmentResponse{value: val, isSet: true}
}

func (v NullableActivitiesAttachmentResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActivitiesAttachmentResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


