/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationCommandOptionNumberChoiceResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationCommandOptionNumberChoiceResponse{}

// ApplicationCommandOptionNumberChoiceResponse struct for ApplicationCommandOptionNumberChoiceResponse
type ApplicationCommandOptionNumberChoiceResponse struct {
	Name string `json:"name"`
	NameLocalized NullableString `json:"name_localized,omitempty"`
	NameLocalizations map[string]string `json:"name_localizations,omitempty"`
	Value float64 `json:"value"`
}

type _ApplicationCommandOptionNumberChoiceResponse ApplicationCommandOptionNumberChoiceResponse

// NewApplicationCommandOptionNumberChoiceResponse instantiates a new ApplicationCommandOptionNumberChoiceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCommandOptionNumberChoiceResponse(name string, value float64) *ApplicationCommandOptionNumberChoiceResponse {
	this := ApplicationCommandOptionNumberChoiceResponse{}
	this.Name = name
	this.Value = value
	return &this
}

// NewApplicationCommandOptionNumberChoiceResponseWithDefaults instantiates a new ApplicationCommandOptionNumberChoiceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCommandOptionNumberChoiceResponseWithDefaults() *ApplicationCommandOptionNumberChoiceResponse {
	this := ApplicationCommandOptionNumberChoiceResponse{}
	return &this
}

// GetName returns the Name field value
func (o *ApplicationCommandOptionNumberChoiceResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApplicationCommandOptionNumberChoiceResponse) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApplicationCommandOptionNumberChoiceResponse) SetName(v string) {
	o.Name = v
}

// GetNameLocalized returns the NameLocalized field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApplicationCommandOptionNumberChoiceResponse) GetNameLocalized() string {
	if o == nil || IsNil(o.NameLocalized.Get()) {
		var ret string
		return ret
	}
	return *o.NameLocalized.Get()
}

// GetNameLocalizedOk returns a tuple with the NameLocalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApplicationCommandOptionNumberChoiceResponse) GetNameLocalizedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NameLocalized.Get(), o.NameLocalized.IsSet()
}

// HasNameLocalized returns a boolean if a field has been set.
func (o *ApplicationCommandOptionNumberChoiceResponse) HasNameLocalized() bool {
	if o != nil && o.NameLocalized.IsSet() {
		return true
	}

	return false
}

// SetNameLocalized gets a reference to the given NullableString and assigns it to the NameLocalized field.
func (o *ApplicationCommandOptionNumberChoiceResponse) SetNameLocalized(v string) {
	o.NameLocalized.Set(&v)
}
// SetNameLocalizedNil sets the value for NameLocalized to be an explicit nil
func (o *ApplicationCommandOptionNumberChoiceResponse) SetNameLocalizedNil() {
	o.NameLocalized.Set(nil)
}

// UnsetNameLocalized ensures that no value is present for NameLocalized, not even an explicit nil
func (o *ApplicationCommandOptionNumberChoiceResponse) UnsetNameLocalized() {
	o.NameLocalized.Unset()
}

// GetNameLocalizations returns the NameLocalizations field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApplicationCommandOptionNumberChoiceResponse) GetNameLocalizations() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}
	return o.NameLocalizations
}

// GetNameLocalizationsOk returns a tuple with the NameLocalizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApplicationCommandOptionNumberChoiceResponse) GetNameLocalizationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.NameLocalizations) {
		return nil, false
	}
	return &o.NameLocalizations, true
}

// HasNameLocalizations returns a boolean if a field has been set.
func (o *ApplicationCommandOptionNumberChoiceResponse) HasNameLocalizations() bool {
	if o != nil && !IsNil(o.NameLocalizations) {
		return true
	}

	return false
}

// SetNameLocalizations gets a reference to the given map[string]string and assigns it to the NameLocalizations field.
func (o *ApplicationCommandOptionNumberChoiceResponse) SetNameLocalizations(v map[string]string) {
	o.NameLocalizations = v
}

// GetValue returns the Value field value
func (o *ApplicationCommandOptionNumberChoiceResponse) GetValue() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *ApplicationCommandOptionNumberChoiceResponse) GetValueOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *ApplicationCommandOptionNumberChoiceResponse) SetValue(v float64) {
	o.Value = v
}

func (o ApplicationCommandOptionNumberChoiceResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationCommandOptionNumberChoiceResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	if o.NameLocalized.IsSet() {
		toSerialize["name_localized"] = o.NameLocalized.Get()
	}
	if o.NameLocalizations != nil {
		toSerialize["name_localizations"] = o.NameLocalizations
	}
	toSerialize["value"] = o.Value
	return toSerialize, nil
}

func (o *ApplicationCommandOptionNumberChoiceResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationCommandOptionNumberChoiceResponse := _ApplicationCommandOptionNumberChoiceResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationCommandOptionNumberChoiceResponse)

	if err != nil {
		return err
	}

	*o = ApplicationCommandOptionNumberChoiceResponse(varApplicationCommandOptionNumberChoiceResponse)

	return err
}

type NullableApplicationCommandOptionNumberChoiceResponse struct {
	value *ApplicationCommandOptionNumberChoiceResponse
	isSet bool
}

func (v NullableApplicationCommandOptionNumberChoiceResponse) Get() *ApplicationCommandOptionNumberChoiceResponse {
	return v.value
}

func (v *NullableApplicationCommandOptionNumberChoiceResponse) Set(val *ApplicationCommandOptionNumberChoiceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCommandOptionNumberChoiceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCommandOptionNumberChoiceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCommandOptionNumberChoiceResponse(val *ApplicationCommandOptionNumberChoiceResponse) *NullableApplicationCommandOptionNumberChoiceResponse {
	return &NullableApplicationCommandOptionNumberChoiceResponse{value: val, isSet: true}
}

func (v NullableApplicationCommandOptionNumberChoiceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCommandOptionNumberChoiceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


