/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the GuildScheduledEventEntityTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildScheduledEventEntityTypes{}

// GuildScheduledEventEntityTypes struct for GuildScheduledEventEntityTypes
type GuildScheduledEventEntityTypes struct {
}

// NewGuildScheduledEventEntityTypes instantiates a new GuildScheduledEventEntityTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildScheduledEventEntityTypes() *GuildScheduledEventEntityTypes {
	this := GuildScheduledEventEntityTypes{}
	return &this
}

// NewGuildScheduledEventEntityTypesWithDefaults instantiates a new GuildScheduledEventEntityTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildScheduledEventEntityTypesWithDefaults() *GuildScheduledEventEntityTypes {
	this := GuildScheduledEventEntityTypes{}
	return &this
}

func (o GuildScheduledEventEntityTypes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildScheduledEventEntityTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableGuildScheduledEventEntityTypes struct {
	value *GuildScheduledEventEntityTypes
	isSet bool
}

func (v NullableGuildScheduledEventEntityTypes) Get() *GuildScheduledEventEntityTypes {
	return v.value
}

func (v *NullableGuildScheduledEventEntityTypes) Set(val *GuildScheduledEventEntityTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildScheduledEventEntityTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildScheduledEventEntityTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildScheduledEventEntityTypes(val *GuildScheduledEventEntityTypes) *NullableGuildScheduledEventEntityTypes {
	return &NullableGuildScheduledEventEntityTypes{value: val, isSet: true}
}

func (v NullableGuildScheduledEventEntityTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildScheduledEventEntityTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


