/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the IntegrationExpireGracePeriodTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationExpireGracePeriodTypes{}

// IntegrationExpireGracePeriodTypes struct for IntegrationExpireGracePeriodTypes
type IntegrationExpireGracePeriodTypes struct {
}

// NewIntegrationExpireGracePeriodTypes instantiates a new IntegrationExpireGracePeriodTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationExpireGracePeriodTypes() *IntegrationExpireGracePeriodTypes {
	this := IntegrationExpireGracePeriodTypes{}
	return &this
}

// NewIntegrationExpireGracePeriodTypesWithDefaults instantiates a new IntegrationExpireGracePeriodTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationExpireGracePeriodTypesWithDefaults() *IntegrationExpireGracePeriodTypes {
	this := IntegrationExpireGracePeriodTypes{}
	return &this
}

func (o IntegrationExpireGracePeriodTypes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationExpireGracePeriodTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIntegrationExpireGracePeriodTypes struct {
	value *IntegrationExpireGracePeriodTypes
	isSet bool
}

func (v NullableIntegrationExpireGracePeriodTypes) Get() *IntegrationExpireGracePeriodTypes {
	return v.value
}

func (v *NullableIntegrationExpireGracePeriodTypes) Set(val *IntegrationExpireGracePeriodTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationExpireGracePeriodTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationExpireGracePeriodTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationExpireGracePeriodTypes(val *IntegrationExpireGracePeriodTypes) *NullableIntegrationExpireGracePeriodTypes {
	return &NullableIntegrationExpireGracePeriodTypes{value: val, isSet: true}
}

func (v NullableIntegrationExpireGracePeriodTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationExpireGracePeriodTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


