/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApplicationCommandAutocompleteCallbackRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApplicationCommandAutocompleteCallbackRequest{}

// ApplicationCommandAutocompleteCallbackRequest struct for ApplicationCommandAutocompleteCallbackRequest
type ApplicationCommandAutocompleteCallbackRequest struct {
	Type InteractionCallbackTypes `json:"type"`
	Data ApplicationCommandAutocompleteCallbackRequestData `json:"data"`
}

type _ApplicationCommandAutocompleteCallbackRequest ApplicationCommandAutocompleteCallbackRequest

// NewApplicationCommandAutocompleteCallbackRequest instantiates a new ApplicationCommandAutocompleteCallbackRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApplicationCommandAutocompleteCallbackRequest(type_ InteractionCallbackTypes, data ApplicationCommandAutocompleteCallbackRequestData) *ApplicationCommandAutocompleteCallbackRequest {
	this := ApplicationCommandAutocompleteCallbackRequest{}
	this.Type = type_
	this.Data = data
	return &this
}

// NewApplicationCommandAutocompleteCallbackRequestWithDefaults instantiates a new ApplicationCommandAutocompleteCallbackRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApplicationCommandAutocompleteCallbackRequestWithDefaults() *ApplicationCommandAutocompleteCallbackRequest {
	this := ApplicationCommandAutocompleteCallbackRequest{}
	return &this
}

// GetType returns the Type field value
func (o *ApplicationCommandAutocompleteCallbackRequest) GetType() InteractionCallbackTypes {
	if o == nil {
		var ret InteractionCallbackTypes
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApplicationCommandAutocompleteCallbackRequest) GetTypeOk() (*InteractionCallbackTypes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApplicationCommandAutocompleteCallbackRequest) SetType(v InteractionCallbackTypes) {
	o.Type = v
}

// GetData returns the Data field value
func (o *ApplicationCommandAutocompleteCallbackRequest) GetData() ApplicationCommandAutocompleteCallbackRequestData {
	if o == nil {
		var ret ApplicationCommandAutocompleteCallbackRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ApplicationCommandAutocompleteCallbackRequest) GetDataOk() (*ApplicationCommandAutocompleteCallbackRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ApplicationCommandAutocompleteCallbackRequest) SetData(v ApplicationCommandAutocompleteCallbackRequestData) {
	o.Data = v
}

func (o ApplicationCommandAutocompleteCallbackRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApplicationCommandAutocompleteCallbackRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ApplicationCommandAutocompleteCallbackRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApplicationCommandAutocompleteCallbackRequest := _ApplicationCommandAutocompleteCallbackRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApplicationCommandAutocompleteCallbackRequest)

	if err != nil {
		return err
	}

	*o = ApplicationCommandAutocompleteCallbackRequest(varApplicationCommandAutocompleteCallbackRequest)

	return err
}

type NullableApplicationCommandAutocompleteCallbackRequest struct {
	value *ApplicationCommandAutocompleteCallbackRequest
	isSet bool
}

func (v NullableApplicationCommandAutocompleteCallbackRequest) Get() *ApplicationCommandAutocompleteCallbackRequest {
	return v.value
}

func (v *NullableApplicationCommandAutocompleteCallbackRequest) Set(val *ApplicationCommandAutocompleteCallbackRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApplicationCommandAutocompleteCallbackRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApplicationCommandAutocompleteCallbackRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApplicationCommandAutocompleteCallbackRequest(val *ApplicationCommandAutocompleteCallbackRequest) *NullableApplicationCommandAutocompleteCallbackRequest {
	return &NullableApplicationCommandAutocompleteCallbackRequest{value: val, isSet: true}
}

func (v NullableApplicationCommandAutocompleteCallbackRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApplicationCommandAutocompleteCallbackRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


