/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the InteractionContextType type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InteractionContextType{}

// InteractionContextType struct for InteractionContextType
type InteractionContextType struct {
}

// NewInteractionContextType instantiates a new InteractionContextType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInteractionContextType() *InteractionContextType {
	this := InteractionContextType{}
	return &this
}

// NewInteractionContextTypeWithDefaults instantiates a new InteractionContextType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInteractionContextTypeWithDefaults() *InteractionContextType {
	this := InteractionContextType{}
	return &this
}

func (o InteractionContextType) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InteractionContextType) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableInteractionContextType struct {
	value *InteractionContextType
	isSet bool
}

func (v NullableInteractionContextType) Get() *InteractionContextType {
	return v.value
}

func (v *NullableInteractionContextType) Set(val *InteractionContextType) {
	v.value = val
	v.isSet = true
}

func (v NullableInteractionContextType) IsSet() bool {
	return v.isSet
}

func (v *NullableInteractionContextType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInteractionContextType(val *InteractionContextType) *NullableInteractionContextType {
	return &NullableInteractionContextType{value: val, isSet: true}
}

func (v NullableInteractionContextType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInteractionContextType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


