/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EntityMetadataExternal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntityMetadataExternal{}

// EntityMetadataExternal struct for EntityMetadataExternal
type EntityMetadataExternal struct {
	Location string `json:"location"`
}

type _EntityMetadataExternal EntityMetadataExternal

// NewEntityMetadataExternal instantiates a new EntityMetadataExternal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntityMetadataExternal(location string) *EntityMetadataExternal {
	this := EntityMetadataExternal{}
	this.Location = location
	return &this
}

// NewEntityMetadataExternalWithDefaults instantiates a new EntityMetadataExternal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntityMetadataExternalWithDefaults() *EntityMetadataExternal {
	this := EntityMetadataExternal{}
	return &this
}

// GetLocation returns the Location field value
func (o *EntityMetadataExternal) GetLocation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *EntityMetadataExternal) GetLocationOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *EntityMetadataExternal) SetLocation(v string) {
	o.Location = v
}

func (o EntityMetadataExternal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntityMetadataExternal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["location"] = o.Location
	return toSerialize, nil
}

func (o *EntityMetadataExternal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEntityMetadataExternal := _EntityMetadataExternal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEntityMetadataExternal)

	if err != nil {
		return err
	}

	*o = EntityMetadataExternal(varEntityMetadataExternal)

	return err
}

type NullableEntityMetadataExternal struct {
	value *EntityMetadataExternal
	isSet bool
}

func (v NullableEntityMetadataExternal) Get() *EntityMetadataExternal {
	return v.value
}

func (v *NullableEntityMetadataExternal) Set(val *EntityMetadataExternal) {
	v.value = val
	v.isSet = true
}

func (v NullableEntityMetadataExternal) IsSet() bool {
	return v.isSet
}

func (v *NullableEntityMetadataExternal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntityMetadataExternal(val *EntityMetadataExternal) *NullableEntityMetadataExternal {
	return &NullableEntityMetadataExternal{value: val, isSet: true}
}

func (v NullableEntityMetadataExternal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntityMetadataExternal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


