/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the GuildRoleTagsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GuildRoleTagsResponse{}

// GuildRoleTagsResponse struct for GuildRoleTagsResponse
type GuildRoleTagsResponse struct {
	PremiumSubscriber *nil `json:"premium_subscriber,omitempty"`
	BotId *string `json:"bot_id,omitempty" validate:"regexp=^(0|[1-9][0-9]*)$"`
	IntegrationId *string `json:"integration_id,omitempty" validate:"regexp=^(0|[1-9][0-9]*)$"`
	SubscriptionListingId *string `json:"subscription_listing_id,omitempty" validate:"regexp=^(0|[1-9][0-9]*)$"`
	AvailableForPurchase *nil `json:"available_for_purchase,omitempty"`
	GuildConnections *nil `json:"guild_connections,omitempty"`
}

// NewGuildRoleTagsResponse instantiates a new GuildRoleTagsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGuildRoleTagsResponse() *GuildRoleTagsResponse {
	this := GuildRoleTagsResponse{}
	return &this
}

// NewGuildRoleTagsResponseWithDefaults instantiates a new GuildRoleTagsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGuildRoleTagsResponseWithDefaults() *GuildRoleTagsResponse {
	this := GuildRoleTagsResponse{}
	return &this
}

// GetPremiumSubscriber returns the PremiumSubscriber field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetPremiumSubscriber() nil {
	if o == nil || IsNil(o.PremiumSubscriber) {
		var ret nil
		return ret
	}
	return *o.PremiumSubscriber
}

// GetPremiumSubscriberOk returns a tuple with the PremiumSubscriber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetPremiumSubscriberOk() (*nil, bool) {
	if o == nil || IsNil(o.PremiumSubscriber) {
		return nil, false
	}
	return o.PremiumSubscriber, true
}

// HasPremiumSubscriber returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasPremiumSubscriber() bool {
	if o != nil && !IsNil(o.PremiumSubscriber) {
		return true
	}

	return false
}

// SetPremiumSubscriber gets a reference to the given nil and assigns it to the PremiumSubscriber field.
func (o *GuildRoleTagsResponse) SetPremiumSubscriber(v nil) {
	o.PremiumSubscriber = &v
}

// GetBotId returns the BotId field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetBotId() string {
	if o == nil || IsNil(o.BotId) {
		var ret string
		return ret
	}
	return *o.BotId
}

// GetBotIdOk returns a tuple with the BotId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetBotIdOk() (*string, bool) {
	if o == nil || IsNil(o.BotId) {
		return nil, false
	}
	return o.BotId, true
}

// HasBotId returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasBotId() bool {
	if o != nil && !IsNil(o.BotId) {
		return true
	}

	return false
}

// SetBotId gets a reference to the given string and assigns it to the BotId field.
func (o *GuildRoleTagsResponse) SetBotId(v string) {
	o.BotId = &v
}

// GetIntegrationId returns the IntegrationId field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetIntegrationId() string {
	if o == nil || IsNil(o.IntegrationId) {
		var ret string
		return ret
	}
	return *o.IntegrationId
}

// GetIntegrationIdOk returns a tuple with the IntegrationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetIntegrationIdOk() (*string, bool) {
	if o == nil || IsNil(o.IntegrationId) {
		return nil, false
	}
	return o.IntegrationId, true
}

// HasIntegrationId returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasIntegrationId() bool {
	if o != nil && !IsNil(o.IntegrationId) {
		return true
	}

	return false
}

// SetIntegrationId gets a reference to the given string and assigns it to the IntegrationId field.
func (o *GuildRoleTagsResponse) SetIntegrationId(v string) {
	o.IntegrationId = &v
}

// GetSubscriptionListingId returns the SubscriptionListingId field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetSubscriptionListingId() string {
	if o == nil || IsNil(o.SubscriptionListingId) {
		var ret string
		return ret
	}
	return *o.SubscriptionListingId
}

// GetSubscriptionListingIdOk returns a tuple with the SubscriptionListingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetSubscriptionListingIdOk() (*string, bool) {
	if o == nil || IsNil(o.SubscriptionListingId) {
		return nil, false
	}
	return o.SubscriptionListingId, true
}

// HasSubscriptionListingId returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasSubscriptionListingId() bool {
	if o != nil && !IsNil(o.SubscriptionListingId) {
		return true
	}

	return false
}

// SetSubscriptionListingId gets a reference to the given string and assigns it to the SubscriptionListingId field.
func (o *GuildRoleTagsResponse) SetSubscriptionListingId(v string) {
	o.SubscriptionListingId = &v
}

// GetAvailableForPurchase returns the AvailableForPurchase field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetAvailableForPurchase() nil {
	if o == nil || IsNil(o.AvailableForPurchase) {
		var ret nil
		return ret
	}
	return *o.AvailableForPurchase
}

// GetAvailableForPurchaseOk returns a tuple with the AvailableForPurchase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetAvailableForPurchaseOk() (*nil, bool) {
	if o == nil || IsNil(o.AvailableForPurchase) {
		return nil, false
	}
	return o.AvailableForPurchase, true
}

// HasAvailableForPurchase returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasAvailableForPurchase() bool {
	if o != nil && !IsNil(o.AvailableForPurchase) {
		return true
	}

	return false
}

// SetAvailableForPurchase gets a reference to the given nil and assigns it to the AvailableForPurchase field.
func (o *GuildRoleTagsResponse) SetAvailableForPurchase(v nil) {
	o.AvailableForPurchase = &v
}

// GetGuildConnections returns the GuildConnections field value if set, zero value otherwise.
func (o *GuildRoleTagsResponse) GetGuildConnections() nil {
	if o == nil || IsNil(o.GuildConnections) {
		var ret nil
		return ret
	}
	return *o.GuildConnections
}

// GetGuildConnectionsOk returns a tuple with the GuildConnections field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GuildRoleTagsResponse) GetGuildConnectionsOk() (*nil, bool) {
	if o == nil || IsNil(o.GuildConnections) {
		return nil, false
	}
	return o.GuildConnections, true
}

// HasGuildConnections returns a boolean if a field has been set.
func (o *GuildRoleTagsResponse) HasGuildConnections() bool {
	if o != nil && !IsNil(o.GuildConnections) {
		return true
	}

	return false
}

// SetGuildConnections gets a reference to the given nil and assigns it to the GuildConnections field.
func (o *GuildRoleTagsResponse) SetGuildConnections(v nil) {
	o.GuildConnections = &v
}

func (o GuildRoleTagsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GuildRoleTagsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PremiumSubscriber) {
		toSerialize["premium_subscriber"] = o.PremiumSubscriber
	}
	if !IsNil(o.BotId) {
		toSerialize["bot_id"] = o.BotId
	}
	if !IsNil(o.IntegrationId) {
		toSerialize["integration_id"] = o.IntegrationId
	}
	if !IsNil(o.SubscriptionListingId) {
		toSerialize["subscription_listing_id"] = o.SubscriptionListingId
	}
	if !IsNil(o.AvailableForPurchase) {
		toSerialize["available_for_purchase"] = o.AvailableForPurchase
	}
	if !IsNil(o.GuildConnections) {
		toSerialize["guild_connections"] = o.GuildConnections
	}
	return toSerialize, nil
}

type NullableGuildRoleTagsResponse struct {
	value *GuildRoleTagsResponse
	isSet bool
}

func (v NullableGuildRoleTagsResponse) Get() *GuildRoleTagsResponse {
	return v.value
}

func (v *NullableGuildRoleTagsResponse) Set(val *GuildRoleTagsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGuildRoleTagsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGuildRoleTagsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGuildRoleTagsResponse(val *GuildRoleTagsResponse) *NullableGuildRoleTagsResponse {
	return &NullableGuildRoleTagsResponse{value: val, isSet: true}
}

func (v NullableGuildRoleTagsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGuildRoleTagsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


