/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BlockMessageActionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BlockMessageActionResponse{}

// BlockMessageActionResponse struct for BlockMessageActionResponse
type BlockMessageActionResponse struct {
	Type AutomodActionType `json:"type"`
	Metadata BlockMessageActionMetadataResponse `json:"metadata"`
}

type _BlockMessageActionResponse BlockMessageActionResponse

// NewBlockMessageActionResponse instantiates a new BlockMessageActionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBlockMessageActionResponse(type_ AutomodActionType, metadata BlockMessageActionMetadataResponse) *BlockMessageActionResponse {
	this := BlockMessageActionResponse{}
	this.Type = type_
	this.Metadata = metadata
	return &this
}

// NewBlockMessageActionResponseWithDefaults instantiates a new BlockMessageActionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBlockMessageActionResponseWithDefaults() *BlockMessageActionResponse {
	this := BlockMessageActionResponse{}
	return &this
}

// GetType returns the Type field value
func (o *BlockMessageActionResponse) GetType() AutomodActionType {
	if o == nil {
		var ret AutomodActionType
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BlockMessageActionResponse) GetTypeOk() (*AutomodActionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BlockMessageActionResponse) SetType(v AutomodActionType) {
	o.Type = v
}

// GetMetadata returns the Metadata field value
func (o *BlockMessageActionResponse) GetMetadata() BlockMessageActionMetadataResponse {
	if o == nil {
		var ret BlockMessageActionMetadataResponse
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *BlockMessageActionResponse) GetMetadataOk() (*BlockMessageActionMetadataResponse, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *BlockMessageActionResponse) SetMetadata(v BlockMessageActionMetadataResponse) {
	o.Metadata = v
}

func (o BlockMessageActionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BlockMessageActionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["metadata"] = o.Metadata
	return toSerialize, nil
}

func (o *BlockMessageActionResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"metadata",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBlockMessageActionResponse := _BlockMessageActionResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBlockMessageActionResponse)

	if err != nil {
		return err
	}

	*o = BlockMessageActionResponse(varBlockMessageActionResponse)

	return err
}

type NullableBlockMessageActionResponse struct {
	value *BlockMessageActionResponse
	isSet bool
}

func (v NullableBlockMessageActionResponse) Get() *BlockMessageActionResponse {
	return v.value
}

func (v *NullableBlockMessageActionResponse) Set(val *BlockMessageActionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBlockMessageActionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBlockMessageActionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBlockMessageActionResponse(val *BlockMessageActionResponse) *NullableBlockMessageActionResponse {
	return &NullableBlockMessageActionResponse{value: val, isSet: true}
}

func (v NullableBlockMessageActionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBlockMessageActionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


