/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// BasicMessageResponseComponentsInner - struct for BasicMessageResponseComponentsInner
type BasicMessageResponseComponentsInner struct {
	MessageComponentActionRowResponse *MessageComponentActionRowResponse
	MessageComponentButtonResponse *MessageComponentButtonResponse
	MessageComponentChannelSelectResponse *MessageComponentChannelSelectResponse
	MessageComponentInputTextResponse *MessageComponentInputTextResponse
	MessageComponentMentionableSelectResponse *MessageComponentMentionableSelectResponse
	MessageComponentRoleSelectResponse *MessageComponentRoleSelectResponse
	MessageComponentStringSelectResponse *MessageComponentStringSelectResponse
	MessageComponentUserSelectResponse *MessageComponentUserSelectResponse
}

// MessageComponentActionRowResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentActionRowResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentActionRowResponseAsBasicMessageResponseComponentsInner(v *MessageComponentActionRowResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentActionRowResponse: v,
	}
}

// MessageComponentButtonResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentButtonResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentButtonResponseAsBasicMessageResponseComponentsInner(v *MessageComponentButtonResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentButtonResponse: v,
	}
}

// MessageComponentChannelSelectResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentChannelSelectResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentChannelSelectResponseAsBasicMessageResponseComponentsInner(v *MessageComponentChannelSelectResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentChannelSelectResponse: v,
	}
}

// MessageComponentInputTextResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentInputTextResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentInputTextResponseAsBasicMessageResponseComponentsInner(v *MessageComponentInputTextResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentInputTextResponse: v,
	}
}

// MessageComponentMentionableSelectResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentMentionableSelectResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentMentionableSelectResponseAsBasicMessageResponseComponentsInner(v *MessageComponentMentionableSelectResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentMentionableSelectResponse: v,
	}
}

// MessageComponentRoleSelectResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentRoleSelectResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentRoleSelectResponseAsBasicMessageResponseComponentsInner(v *MessageComponentRoleSelectResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentRoleSelectResponse: v,
	}
}

// MessageComponentStringSelectResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentStringSelectResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentStringSelectResponseAsBasicMessageResponseComponentsInner(v *MessageComponentStringSelectResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentStringSelectResponse: v,
	}
}

// MessageComponentUserSelectResponseAsBasicMessageResponseComponentsInner is a convenience function that returns MessageComponentUserSelectResponse wrapped in BasicMessageResponseComponentsInner
func MessageComponentUserSelectResponseAsBasicMessageResponseComponentsInner(v *MessageComponentUserSelectResponse) BasicMessageResponseComponentsInner {
	return BasicMessageResponseComponentsInner{
		MessageComponentUserSelectResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *BasicMessageResponseComponentsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MessageComponentActionRowResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentActionRowResponse)
	if err == nil {
		jsonMessageComponentActionRowResponse, _ := json.Marshal(dst.MessageComponentActionRowResponse)
		if string(jsonMessageComponentActionRowResponse) == "{}" { // empty struct
			dst.MessageComponentActionRowResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentActionRowResponse); err != nil {
				dst.MessageComponentActionRowResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentActionRowResponse = nil
	}

	// try to unmarshal data into MessageComponentButtonResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentButtonResponse)
	if err == nil {
		jsonMessageComponentButtonResponse, _ := json.Marshal(dst.MessageComponentButtonResponse)
		if string(jsonMessageComponentButtonResponse) == "{}" { // empty struct
			dst.MessageComponentButtonResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentButtonResponse); err != nil {
				dst.MessageComponentButtonResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentButtonResponse = nil
	}

	// try to unmarshal data into MessageComponentChannelSelectResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentChannelSelectResponse)
	if err == nil {
		jsonMessageComponentChannelSelectResponse, _ := json.Marshal(dst.MessageComponentChannelSelectResponse)
		if string(jsonMessageComponentChannelSelectResponse) == "{}" { // empty struct
			dst.MessageComponentChannelSelectResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentChannelSelectResponse); err != nil {
				dst.MessageComponentChannelSelectResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentChannelSelectResponse = nil
	}

	// try to unmarshal data into MessageComponentInputTextResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentInputTextResponse)
	if err == nil {
		jsonMessageComponentInputTextResponse, _ := json.Marshal(dst.MessageComponentInputTextResponse)
		if string(jsonMessageComponentInputTextResponse) == "{}" { // empty struct
			dst.MessageComponentInputTextResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentInputTextResponse); err != nil {
				dst.MessageComponentInputTextResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentInputTextResponse = nil
	}

	// try to unmarshal data into MessageComponentMentionableSelectResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentMentionableSelectResponse)
	if err == nil {
		jsonMessageComponentMentionableSelectResponse, _ := json.Marshal(dst.MessageComponentMentionableSelectResponse)
		if string(jsonMessageComponentMentionableSelectResponse) == "{}" { // empty struct
			dst.MessageComponentMentionableSelectResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentMentionableSelectResponse); err != nil {
				dst.MessageComponentMentionableSelectResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentMentionableSelectResponse = nil
	}

	// try to unmarshal data into MessageComponentRoleSelectResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentRoleSelectResponse)
	if err == nil {
		jsonMessageComponentRoleSelectResponse, _ := json.Marshal(dst.MessageComponentRoleSelectResponse)
		if string(jsonMessageComponentRoleSelectResponse) == "{}" { // empty struct
			dst.MessageComponentRoleSelectResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentRoleSelectResponse); err != nil {
				dst.MessageComponentRoleSelectResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentRoleSelectResponse = nil
	}

	// try to unmarshal data into MessageComponentStringSelectResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentStringSelectResponse)
	if err == nil {
		jsonMessageComponentStringSelectResponse, _ := json.Marshal(dst.MessageComponentStringSelectResponse)
		if string(jsonMessageComponentStringSelectResponse) == "{}" { // empty struct
			dst.MessageComponentStringSelectResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentStringSelectResponse); err != nil {
				dst.MessageComponentStringSelectResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentStringSelectResponse = nil
	}

	// try to unmarshal data into MessageComponentUserSelectResponse
	err = newStrictDecoder(data).Decode(&dst.MessageComponentUserSelectResponse)
	if err == nil {
		jsonMessageComponentUserSelectResponse, _ := json.Marshal(dst.MessageComponentUserSelectResponse)
		if string(jsonMessageComponentUserSelectResponse) == "{}" { // empty struct
			dst.MessageComponentUserSelectResponse = nil
		} else {
			if err = validator.Validate(dst.MessageComponentUserSelectResponse); err != nil {
				dst.MessageComponentUserSelectResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.MessageComponentUserSelectResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MessageComponentActionRowResponse = nil
		dst.MessageComponentButtonResponse = nil
		dst.MessageComponentChannelSelectResponse = nil
		dst.MessageComponentInputTextResponse = nil
		dst.MessageComponentMentionableSelectResponse = nil
		dst.MessageComponentRoleSelectResponse = nil
		dst.MessageComponentStringSelectResponse = nil
		dst.MessageComponentUserSelectResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(BasicMessageResponseComponentsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(BasicMessageResponseComponentsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src BasicMessageResponseComponentsInner) MarshalJSON() ([]byte, error) {
	if src.MessageComponentActionRowResponse != nil {
		return json.Marshal(&src.MessageComponentActionRowResponse)
	}

	if src.MessageComponentButtonResponse != nil {
		return json.Marshal(&src.MessageComponentButtonResponse)
	}

	if src.MessageComponentChannelSelectResponse != nil {
		return json.Marshal(&src.MessageComponentChannelSelectResponse)
	}

	if src.MessageComponentInputTextResponse != nil {
		return json.Marshal(&src.MessageComponentInputTextResponse)
	}

	if src.MessageComponentMentionableSelectResponse != nil {
		return json.Marshal(&src.MessageComponentMentionableSelectResponse)
	}

	if src.MessageComponentRoleSelectResponse != nil {
		return json.Marshal(&src.MessageComponentRoleSelectResponse)
	}

	if src.MessageComponentStringSelectResponse != nil {
		return json.Marshal(&src.MessageComponentStringSelectResponse)
	}

	if src.MessageComponentUserSelectResponse != nil {
		return json.Marshal(&src.MessageComponentUserSelectResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *BasicMessageResponseComponentsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.MessageComponentActionRowResponse != nil {
		return obj.MessageComponentActionRowResponse
	}

	if obj.MessageComponentButtonResponse != nil {
		return obj.MessageComponentButtonResponse
	}

	if obj.MessageComponentChannelSelectResponse != nil {
		return obj.MessageComponentChannelSelectResponse
	}

	if obj.MessageComponentInputTextResponse != nil {
		return obj.MessageComponentInputTextResponse
	}

	if obj.MessageComponentMentionableSelectResponse != nil {
		return obj.MessageComponentMentionableSelectResponse
	}

	if obj.MessageComponentRoleSelectResponse != nil {
		return obj.MessageComponentRoleSelectResponse
	}

	if obj.MessageComponentStringSelectResponse != nil {
		return obj.MessageComponentStringSelectResponse
	}

	if obj.MessageComponentUserSelectResponse != nil {
		return obj.MessageComponentUserSelectResponse
	}

	// all schemas are nil
	return nil
}

type NullableBasicMessageResponseComponentsInner struct {
	value *BasicMessageResponseComponentsInner
	isSet bool
}

func (v NullableBasicMessageResponseComponentsInner) Get() *BasicMessageResponseComponentsInner {
	return v.value
}

func (v *NullableBasicMessageResponseComponentsInner) Set(val *BasicMessageResponseComponentsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableBasicMessageResponseComponentsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableBasicMessageResponseComponentsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBasicMessageResponseComponentsInner(val *BasicMessageResponseComponentsInner) *NullableBasicMessageResponseComponentsInner {
	return &NullableBasicMessageResponseComponentsInner{value: val, isSet: true}
}

func (v NullableBasicMessageResponseComponentsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBasicMessageResponseComponentsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


