/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the IntegrationTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IntegrationTypes{}

// IntegrationTypes struct for IntegrationTypes
type IntegrationTypes struct {
}

// NewIntegrationTypes instantiates a new IntegrationTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIntegrationTypes() *IntegrationTypes {
	this := IntegrationTypes{}
	return &this
}

// NewIntegrationTypesWithDefaults instantiates a new IntegrationTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIntegrationTypesWithDefaults() *IntegrationTypes {
	this := IntegrationTypes{}
	return &this
}

func (o IntegrationTypes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IntegrationTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableIntegrationTypes struct {
	value *IntegrationTypes
	isSet bool
}

func (v NullableIntegrationTypes) Get() *IntegrationTypes {
	return v.value
}

func (v *NullableIntegrationTypes) Set(val *IntegrationTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableIntegrationTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableIntegrationTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIntegrationTypes(val *IntegrationTypes) *NullableIntegrationTypes {
	return &NullableIntegrationTypes{value: val, isSet: true}
}

func (v NullableIntegrationTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIntegrationTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


