/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the AvailableLocalesEnum type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AvailableLocalesEnum{}

// AvailableLocalesEnum struct for AvailableLocalesEnum
type AvailableLocalesEnum struct {
}

// NewAvailableLocalesEnum instantiates a new AvailableLocalesEnum object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAvailableLocalesEnum() *AvailableLocalesEnum {
	this := AvailableLocalesEnum{}
	return &this
}

// NewAvailableLocalesEnumWithDefaults instantiates a new AvailableLocalesEnum object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAvailableLocalesEnumWithDefaults() *AvailableLocalesEnum {
	this := AvailableLocalesEnum{}
	return &this
}

func (o AvailableLocalesEnum) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AvailableLocalesEnum) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableAvailableLocalesEnum struct {
	value *AvailableLocalesEnum
	isSet bool
}

func (v NullableAvailableLocalesEnum) Get() *AvailableLocalesEnum {
	return v.value
}

func (v *NullableAvailableLocalesEnum) Set(val *AvailableLocalesEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableAvailableLocalesEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableAvailableLocalesEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAvailableLocalesEnum(val *AvailableLocalesEnum) *NullableAvailableLocalesEnum {
	return &NullableAvailableLocalesEnum{value: val, isSet: true}
}

func (v NullableAvailableLocalesEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAvailableLocalesEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


