/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the PollMedia type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PollMedia{}

// PollMedia struct for PollMedia
type PollMedia struct {
	Text NullableString `json:"text,omitempty"`
	Emoji NullablePollEmoji `json:"emoji,omitempty"`
}

// NewPollMedia instantiates a new PollMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPollMedia() *PollMedia {
	this := PollMedia{}
	return &this
}

// NewPollMediaWithDefaults instantiates a new PollMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPollMediaWithDefaults() *PollMedia {
	this := PollMedia{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PollMedia) GetText() string {
	if o == nil || IsNil(o.Text.Get()) {
		var ret string
		return ret
	}
	return *o.Text.Get()
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PollMedia) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Text.Get(), o.Text.IsSet()
}

// HasText returns a boolean if a field has been set.
func (o *PollMedia) HasText() bool {
	if o != nil && o.Text.IsSet() {
		return true
	}

	return false
}

// SetText gets a reference to the given NullableString and assigns it to the Text field.
func (o *PollMedia) SetText(v string) {
	o.Text.Set(&v)
}
// SetTextNil sets the value for Text to be an explicit nil
func (o *PollMedia) SetTextNil() {
	o.Text.Set(nil)
}

// UnsetText ensures that no value is present for Text, not even an explicit nil
func (o *PollMedia) UnsetText() {
	o.Text.Unset()
}

// GetEmoji returns the Emoji field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PollMedia) GetEmoji() PollEmoji {
	if o == nil || IsNil(o.Emoji.Get()) {
		var ret PollEmoji
		return ret
	}
	return *o.Emoji.Get()
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PollMedia) GetEmojiOk() (*PollEmoji, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emoji.Get(), o.Emoji.IsSet()
}

// HasEmoji returns a boolean if a field has been set.
func (o *PollMedia) HasEmoji() bool {
	if o != nil && o.Emoji.IsSet() {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given NullablePollEmoji and assigns it to the Emoji field.
func (o *PollMedia) SetEmoji(v PollEmoji) {
	o.Emoji.Set(&v)
}
// SetEmojiNil sets the value for Emoji to be an explicit nil
func (o *PollMedia) SetEmojiNil() {
	o.Emoji.Set(nil)
}

// UnsetEmoji ensures that no value is present for Emoji, not even an explicit nil
func (o *PollMedia) UnsetEmoji() {
	o.Emoji.Unset()
}

func (o PollMedia) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PollMedia) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Text.IsSet() {
		toSerialize["text"] = o.Text.Get()
	}
	if o.Emoji.IsSet() {
		toSerialize["emoji"] = o.Emoji.Get()
	}
	return toSerialize, nil
}

type NullablePollMedia struct {
	value *PollMedia
	isSet bool
}

func (v NullablePollMedia) Get() *PollMedia {
	return v.value
}

func (v *NullablePollMedia) Set(val *PollMedia) {
	v.value = val
	v.isSet = true
}

func (v NullablePollMedia) IsSet() bool {
	return v.isSet
}

func (v *NullablePollMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePollMedia(val *PollMedia) *NullablePollMedia {
	return &NullablePollMedia{value: val, isSet: true}
}

func (v NullablePollMedia) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePollMedia) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


