/*
Discord HTTP API (Preview)

Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.

API version: 10
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package discord

import (
	"encoding/json"
)

// checks if the ButtonStyleTypes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ButtonStyleTypes{}

// ButtonStyleTypes struct for ButtonStyleTypes
type ButtonStyleTypes struct {
}

// NewButtonStyleTypes instantiates a new ButtonStyleTypes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewButtonStyleTypes() *ButtonStyleTypes {
	this := ButtonStyleTypes{}
	return &this
}

// NewButtonStyleTypesWithDefaults instantiates a new ButtonStyleTypes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewButtonStyleTypesWithDefaults() *ButtonStyleTypes {
	this := ButtonStyleTypes{}
	return &this
}

func (o ButtonStyleTypes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ButtonStyleTypes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	return toSerialize, nil
}

type NullableButtonStyleTypes struct {
	value *ButtonStyleTypes
	isSet bool
}

func (v NullableButtonStyleTypes) Get() *ButtonStyleTypes {
	return v.value
}

func (v *NullableButtonStyleTypes) Set(val *ButtonStyleTypes) {
	v.value = val
	v.isSet = true
}

func (v NullableButtonStyleTypes) IsSet() bool {
	return v.isSet
}

func (v *NullableButtonStyleTypes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableButtonStyleTypes(val *ButtonStyleTypes) *NullableButtonStyleTypes {
	return &NullableButtonStyleTypes{value: val, isSet: true}
}

func (v NullableButtonStyleTypes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableButtonStyleTypes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


